{{- if and .Values.state.dsn (not .Values.state.dsnSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cfunc.fullname" . }}-state
  labels: {{- include "cfunc.labels" . | nindent 4 }}
type: Opaque
stringData:
  dsn: {{ .Values.state.dsn | quote }}
{{- end }}
---
{{- if and .Values.gateway.adminToken (not .Values.gateway.adminTokenSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cfunc.fullname" . }}-admin
  labels: {{- include "cfunc.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.gateway.adminToken | quote }}
{{- end }}
---
{{- if and .Values.builder.enabled .Values.builder.token (not .Values.builder.tokenSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cfunc.fullname" . }}-builder
  labels: {{- include "cfunc.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.builder.token | quote }}
{{- end }}
